#ifndef TOKENTYPE_H
#define TOKENTYPE_H

enum class TokenType {
    KEYWORD,
    INTEGER_LITERAL,
    FLOAT_LITERAL,
    HEX_LITERAL,
    STRING_LITERAL,
    CHAR_LITERAL,
    BOOLEAN_LITERAL,
    IDENTIFIER,
    OPERATOR,
    SEPARATOR,
    LINE_COMMENT,
    BLOCK_COMMENT,
    PREPROCESSOR,
    UNRECOGNIZED,
    UNTERMINATED_STRING,
    UNTERMINATED_CHAR,
    UNTERMINATED_COMMENT
};

#endif